spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste_processadora
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa: 
    hibernate:
      naming: 
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jooq: 
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization: 
      write-dates-as-timestamps: false

application: 
  max: 
    attempt: 
      authorization-code: 5
  socket: 
    tcp: 
      port: 9999