version: "3"
services: 
  postgresdb:
    image: postgres:10.4
    restart: always
    environment: 
      - POSTGRES_DB=teste_processadora
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports: 
      - "5432:5432"

  teste-processadora:
    build: 
      context: ../../../
    restart: always
    ports: 
      - "8080:8080"
      - "9999:9999"
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/teste_processadora
    links: 
      - postgresdb