version: "3"
services: 
  postgres:
    image: postgres:10.4
    restart: always
    environment: 
      - POSTGRES_DB=teste_processadora
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports: 
      - "5432:5432"